# Generated by Django 4.2 on 2023-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailverify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmailotp',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobileotp',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
